# Generated by Django 4.0.6 on 2023-01-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_myuser_school_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
    ]
