# Generated by Django 4.0.6 on 2023-02-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
