# Generated by Django 4.0.6 on 2023-02-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userinfo_email_alter_myuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
