# Generated by Django 4.0.6 on 2023-02-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_userinfo_email_alter_myuser_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='email',
            new_name='name',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
